import type { Layer } from "../template/schema";

// Per-skin asset registry. Layered architecture:
//   frame              = AI faceplate (bezel + blank panel, no controls/screens)
//   sprites/           = AI control sprites WITH STATES (switch-off/on, knob,
//                        button, thumb) — composited live by React
//   screens + content  = CSS recessed screens with live React content
// CSS approximations are the fallback when a layer is missing.
export interface SkinAssets {
  id: string;
  name: string;
  blurb: string;
  has: Layer[];
  // the generated frame image bakes in the controls + screens, so React
  // renders only transparent interactive overlays + live screen content
  baked?: boolean;
  // skins whose layout was EXTRACTED from a freeform design carry their own
  // template (fetched at runtime) instead of the canonical one
  templateUrl?: string;
  // CSS palette to use (the [data-skin] value); defaults to id.
  style?: string;
  // wild-shaped skins with CV-detected screen regions
  live?: boolean;
  // AI control sprites with states exist under /skins/<id>/sprites/
  sprites?: boolean;
  // sprite/palette donor only — not shown in the skin list
  hidden?: boolean;
  // sprites/btn-{prev,play,pause,stop,next}.png exist — molded transport faces
  molded?: boolean;
}

export function skinLive(id: string): boolean {
  return !!skinList.find((x) => x.id === id)?.live;
}

export function skinStyle(id: string): string {
  const s = skinList.find((x) => x.id === id);
  return s?.style ?? id;
}

// sprites resolve through `style`, so a wild body (own frame/template) mounts
// its base style's control sprites
export function skinSprites(id: string): boolean {
  const sid = skinStyle(id);
  return !!skinList.find((x) => x.id === sid)?.sprites;
}

export function skinMolded(id: string): boolean {
  const sid = skinStyle(id);
  return !!skinList.find((x) => x.id === sid)?.molded;
}

export const skinList: SkinAssets[] = [
  // sprite/palette donors (not listed)
  { id: "winamp",  name: "Winamp Classic", blurb: "", has: ["frame"], sprites: true, molded: true, hidden: true },
  { id: "toilet",  name: "Porcelain",      blurb: "", has: ["frame"], sprites: true, molded: true, hidden: true },

  // Baby blue creature — red goggle eyes, gold belt, red teeth-grin visualizer,
  // gold molded transport (shuffle · play · next). Own gold sprites + palette.
  // Generated by `wild_sculpt.py manray manray … manray` + gold sprite passes.
  { id: "manray",  name: "Man Ray ✦",      blurb: "Baby blue creature: red goggle eyes, gold belt, teeth-grin EQ", has: ["frame"], live: true, sprites: true, molded: true, templateUrl: "/skins/manray/template.json" },

  // absurd ✦ — memetic styles with their own sprites + palettes
  { id: "frog",    name: "Froggo ✦",        blurb: "Glossy rubber meme-frog, orange-dot hardware", has: ["frame"], live: true, sprites: true, molded: true, templateUrl: "/skins/frog/template.json" },
  { id: "burger",  name: "Burger Deluxe ✦", blurb: "Sesame bun body, fry-switch, ketchup pointer", has: ["frame"], live: true, sprites: true, molded: true, templateUrl: "/skins/burger/template.json" },
  { id: "bondi",   name: "Bondi G3 ✦",      blurb: "Translucent Y2K plastic, circuit shadows", has: ["frame"], live: true, sprites: true, molded: true, templateUrl: "/skins/bondi/template.json" },
  { id: "biomech", name: "Hive Mind ✦",     blurb: "Giger bone & sinew, bioluminescent veins", has: ["frame"], live: true, sprites: true, molded: true, templateUrl: "/skins/biomech/template.json" },

  // iterations ✦ — new wild_sculpt bodies on the same themes (sprites/palette
  // resolve through `style` to the theme's donor skin)
  { id: "frog2",    name: "Froggo II ✦",      blurb: "New sculpt on the frog theme", has: ["frame"], live: true, style: "frog",    templateUrl: "/skins/frog2/template.json" },
  { id: "burger2",  name: "Double Stack ✦",   blurb: "New sculpt on the burger theme", has: ["frame"], live: true, style: "burger",  templateUrl: "/skins/burger2/template.json" },
  { id: "bondi2",   name: "Bondi Grape ✦",    blurb: "New sculpt on the translucent-plastic theme", has: ["frame"], live: true, style: "bondi",   templateUrl: "/skins/bondi2/template.json" },
  { id: "toilet2",  name: "Porcelain Throne ✦", blurb: "New sculpt on the ceramic theme", has: ["frame"], live: true, style: "toilet",  templateUrl: "/skins/toilet2/template.json" },
  { id: "biomech2", name: "Brood Queen ✦",    blurb: "New sculpt on the Giger theme", has: ["frame"], live: true, style: "biomech", templateUrl: "/skins/biomech2/template.json" },
  { id: "fiend2",   name: "Chrome Demon ✦",   blurb: "New sculpt on the chrome-predator theme", has: ["frame"], live: true, style: "winamp",  templateUrl: "/skins/fiend2/template.json" },

  // era homages ✦ — layout-first capsule/radial with their own sprite sets
  { id: "wmp",  name: "Media Capsule ✦", blurb: "WMP9 XP capsule: ringed dial pod, gel hardware", has: ["frame"], live: true, sprites: true, molded: true, templateUrl: "/skins/wmp/template.json" },
  { id: "halo", name: "Spartan Ring ✦",  blurb: "UNSC armored ring, amber HUD, missile-cover switches", has: ["frame"], live: true, sprites: true, molded: true, templateUrl: "/skins/halo/template.json" },

  // radial ✦ — layout-FIRST: the arc template is drawn before the body, and
  // the image model grows the creature around it (circular seek ring)
  { id: "maw",    name: "Angler Maw ✦",   blurb: "Fanged jaw grown around the dial, seek ring", has: ["frame"], live: true, style: "biomech", templateUrl: "/skins/maw/template.json" },
  { id: "vortex", name: "Chrome Vortex ✦", blurb: "Octopus dome around the dial, seek ring", has: ["frame"], live: true, style: "winamp", templateUrl: "/skins/vortex/template.json" },

  // minimal ✦ — stripped-down "now-playing puck": dial, seek, big play, one knob
  { id: "pebble", name: "Pebble ✦",       blurb: "Minimal frog puck — play / seek / volume only", has: ["frame"], live: true, style: "frog", templateUrl: "/skins/pebble/template.json" },

  // shape-diverse ✦ — relaxed silhouette prompt: deliberately NON-blob bodies
  { id: "obelisk", name: "Bone Totem ✦",  blurb: "Tall vertebral totem, hero-sized play", has: ["frame"], live: true, style: "biomech", templateUrl: "/skins/obelisk/template.json" },
  { id: "slab",   name: "War Slab ✦",     blurb: "Low wide chassis, chrome reference-steered", has: ["frame"], live: true, style: "winamp", templateUrl: "/skins/slab/template.json" },

  // body horror ✦ — divergent takes on the biomech theme family
  { id: "flesh",  name: "Flayed One ✦",   blurb: "Wet muscle & sinew, bone-plate hardware", has: ["frame"], live: true, style: "biomech", templateUrl: "/skins/flesh/template.json" },
  { id: "scarab", name: "Scarab ✦",       blurb: "Black iridescent carapace, crimson seams", has: ["frame"], live: true, style: "biomech", templateUrl: "/skins/scarab/template.json" },
  { id: "spore",  name: "Spore Mother ✦", blurb: "Cordyceps growths, gill ridges, amber glow", has: ["frame"], live: true, style: "biomech", templateUrl: "/skins/spore/template.json" },

  // themed ✦ — generated-from-prompt bodies (radial), sprites via a donor style
  { id: "tomato", name: "Tomato ✦",       blurb: "Cute ripe-tomato pod, leafy stem crown", has: ["frame"], live: true, style: "frog",   templateUrl: "/skins/tomato/template.json" },
  { id: "mexico", name: "El Tri ✦",       blurb: "Mexico football: tricolor, eagle crest, no humans", has: ["frame"], live: true, style: "winamp", templateUrl: "/skins/mexico/template.json" },

  // requested ✦ — themed bodies; sprites/palette via a donor style
  { id: "egypt",    name: "Pharaoh ✦",      blurb: "Gold sarcophagus: lapis nemes, Eye of Horus, scarabs", has: ["frame"], live: true, style: "manray", templateUrl: "/skins/egypt/template.json" },
  { id: "worldcup", name: "World Cup ✦",    blurb: "Gold trophy + football, green-pitch screen", has: ["frame"], live: true, style: "halo",   templateUrl: "/skins/worldcup/template.json" },
  { id: "poophero", name: "Poop Hero ✦",    blurb: "Poop-emoji superhero: googly swirl, red cape, bolt", has: ["frame"], live: true, style: "burger", templateUrl: "/skins/poophero/template.json" },
  { id: "fallout",  name: "Pip-Boy ✦",      blurb: "Fallout industrial: olive metal, amber CRT glow", has: ["frame"], live: true, style: "halo",   templateUrl: "/skins/fallout/template.json" },
  { id: "stonehead",name: "Olmec Head ✦",   blurb: "Colossal basalt stone head, chiselled sockets", has: ["frame"], live: true, style: "winamp", templateUrl: "/skins/stonehead/template.json" },
  { id: "cupcake",  name: "Princess Cake ✦", blurb: "Cupcake: swirl frosting, sprinkles, gold tiara", has: ["frame"], live: true, style: "manray", templateUrl: "/skins/cupcake/template.json" },
  { id: "chacmool", name: "Chacmool ✦",     blurb: "Reclining Mesoamerican basalt statue (ref-matched)", has: ["frame"], live: true, style: "winamp", templateUrl: "/skins/chacmool/template.json" },
];

export function skinTemplateUrl(id: string): string | undefined {
  return skinList.find((x) => x.id === id)?.templateUrl;
}

export function skinBaked(id: string): boolean {
  return !!skinList.find((x) => x.id === id)?.baked;
}

// bump when frames/sprites are regenerated so browsers re-fetch
const ASSET_VERSION = "nb21";
const base = (id: string) => `/skins/${id}`;
export const layerUrl = (id: string, layer: Layer) => `${base(id)}/${layer}.png?v=${ASSET_VERSION}`;
export const spriteUrl = (id: string, name: string) => `${base(skinStyle(id))}/sprites/${name}.png?v=${ASSET_VERSION}`;

export function skinHas(id: string, layer: Layer): boolean {
  const s = skinList.find((x) => x.id === id);
  return !!s?.has.includes(layer);
}
